siteTitle = "Peter Simonsson"
linkPrefix = ""
googleAnalyticsId = "UA-60527-1"
hostName = "https://simonsson.com/"

[[navigation]]
label = "Projects"
path = "/"

[[navigation]]
label = "About"
path = "/about/"
